### ISSUE TITLE
Comment:Step-Intro-Not-worry

### ISSUE THREAD

**Issue by simondujardin** [feathersjs/feathers-guide#3]
Comment:Step-Intro-Not-worry
Hi,

There is an issue with the link in the **Is Feathers production ready? Is it scalable?** section. The link from the **below** word is broken.

Thanks for your nice guide.

Simon DUJARDIN

**Comment by marshallswain** [comment]
Thanks, @simondujardin.  The link to the migrating guide is also now broken since the update to the docs last night.

@simondujardin I actually couldn't find the `below` link.  Could you maybe post a screenshot?

**Comment by eddyystop** [comment]
This was also in the published version on `feathers-docs`. I fixed it there.

**Comment by eddyystop** [comment]
Please look at https://docs.feathersjs.com/guides/step-by-step/production-ready.md

GitBook is tempermental and we can't figure out why it refuses to show this page at this moment.

**Comment by daffl** [comment]
@eddyystop  I removed it in https://github.com/feathersjs/feathers-docs/pull/485 (sorry, thought you had a look at it since you submitted the PR from that branch ;). I moved it to a link in the FAQ (and @marshallswain suggested to put it into a blog post instead).

**Comment by eddyystop** [comment]
There was a reference to it at https://docs.feathersjs.com/guides/step-by-step/intro/not-worry.html#is-feathers-production-ready-is-it-scalable

I added the page back before your comment. GitBook doesn't follow the link to it however, and neither Marshall nor I can figure out why. Another GitBook moment.

Our choices:
- (a) remove above reference can guides/step-by-step/production-ready.md, or
- (b) kick GitBook so it follows the link.

**Comment by marshallswain** [comment]
@eddyystop I'm not sure if this is the case, here, but Gitbook won't compile a `.md` file if it's not linked in the `SUMMARY.md`.

**Comment by eddyystop** [comment]
That was the case. Thanks for cleaning up the mystery.  I'm planning to remove the page as the faq links to a copy of it.

**Comment by eddyystop** [comment]
@simondujardin the page is pointed to by https://docs.feathersjs.com/faq/readme.html#is-feathers-production-ready.

I'm changing the guide to point to that as well.
