### ISSUE TITLE
Comment:Step-Basic-Rest-api-server

### ISSUE THREAD

**Issue by bradenericson** [feathersjs/feathers-guide#8]
Comment:Step-Basic-Rest-api-server:

https://docs.feathersjs.com/guides/step-by-step/basic-feathers/rest-api-server.html#running-the-server

small typo --> We can now **made** REST API calls to the server.
should be --> We can now **make** REST API calls to the server.

**Comment by daffl** [comment]
Thank you. You can directly correct it by clicking the "Edit this page" button at the [top of that page](https://docs.feathersjs.com/guides/step-by-step/basic-feathers/rest-api-server.html).

**Comment by eddyystop** [comment]
What daffl says. But I've already corrected it in https://github.com/feathersjs/feathers-docs/pull/533
