### ISSUE TITLE
Comment:Step-Basic-Real-time

### ISSUE THREAD

**Issue by imdpk** [feathersjs/feathers-guide#9]
The link is invalid for server code:

https://github.com/feathersjs/feathers-docs/blob/master/examples/step/01/WebSocket/1.js

The link that worked for me was:

https://github.com/feathersjs/feathers-docs/blob/master/examples/step/01/websocket/1.js

**Comment by eddyystop** [comment]
Thanks for the catch! There's a PR waiting to fix this.
